### ISSUE TITLE
Support streaming

### ISSUE THREAD

**Issue by thekid** [xp-forge/lambda#22]
Announced in https://aws.amazon.com/de/blogs/compute/introducing-aws-lambda-response-streaming/, April 2023 - supported in Node runtimes.

## JavaScript
Code in *index.js*:
```javascript
exports.handler = awslambda.streamifyResponse(async (event, stream, context) => {
  stream.setContentType("text/plain");
  stream.write("[" + new Date().toISOString() + "] Hello world...\n");

  await new Promise(resolve => setTimeout(resolve, 1000));

  stream.write("[" + new Date().toISOString() + "] ...from Lambda\n");
  stream.end();
});
```

Code in *serverless.yml*:
```yaml
service: node-streaming

provider:
  name: aws
  region: eu-central-1
  profile: default

functions:
  func:
    handler: index.handler
    runtime: nodejs18.x
    description: 'NodeJS Streaming'
    url:
      invokeMode: RESPONSE_STREAM
```

Invocation:
![nodejs-lambda-stream](https://github.com/xp-forge/lambda/assets/696742/a7d03c24-d6a4-4977-984a-6fe09ec7c7ba)

## See also

* https://github.com/serverless/serverless/pull/11907
* https://docs.aws.amazon.com/lambda/latest/dg/configuration-response-streaming.html
* https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html#runtimes-custom-response-streaming
* https://stackoverflow.com/questions/58605901/is-it-possible-to-stream-a-response-from-a-python-aws-lambda
* https://aws.plainenglish.io/aws-lambda-response-stream-optimize-the-app-response-and-experience-344ee444d66a
